Traceback (most recent call last):
  File "testImpossible.py", line 3, in <module>
    impossible()
  File "writeYourProgram.py", line 302, in impossible
    raise errors.ImpossibleError(msg)

Das Unm√∂gliche ist passiert!
