Traceback (most recent call last):
  File "file-test-data/extras/testImpossible.py", line 3, in <module>
    impossible()
  File "code/wypp/writeYourProgram.py", line 331, in impossible
    raise errors.ImpossibleError(msg)

Das Unm√∂gliche ist passiert!
